batch_size: 256
d_ff: 256
d_head: 16
d_model: 64
device: cuda:0
dropout_lstm: 0.3
dropout_rate: 0.3
dynamic_features:
- rf
- tmax
- tmin
dynamic_paths:
- ./data/dynamic/2001.nc
- ./data/dynamic/3008.nc
- ./data/dynamic/4001.nc
- ./data/dynamic/4007.nc
embedding_mode: linear
epochs: 200
experiment_name: train_194_0.0005_28
l2: 0.0001
learning_rate: 0.0005
loss: MSE
lstm_hidden_size: 128
metrics:
- NSE
- KGE
- RMSE
model: transformer
n_decoder_layers: 4
n_encoder_layers: 4
n_heads: 4
optimizer: Adam
past_length: 28
pred_length: 7
run_dir: ./runs/transformer/str4/train_194_0.0005_28
seed: 2222
static_features:
- p_mean
- frac_snow
- high_prec_freq
- high_prec_dur
- low_prec_freq
- low_prec_dur
- elev_mean
- slope_mean
- area_gages2
- frac_forest
static_path: ./data/static/catchment_attributes.csv
test_end_date: '2022-12-31'
test_start_date: '2019-01-01'
tgt_size: 1
train_end_date: '2015-12-31'
train_start_date: '2003-01-01'
validation_end_date: '2022-12-31'
validation_start_date: '2016-01-01'
